REWARDS_URL = "https://rewards.bing.com/"
BING_SEARCH_URL = "https://www.bing.com/search?q={}"
BING_URL = "https://www.bing.com/"
LOGIN_INPUT_CSS_SELECTOR = "input[name='loginfmt']"
PASSWORD_INPUT_CSS_SELECTOR = "input[name='passwd']"
SUBMIT_BUTTON_CSS_SELECTOR = "#idSIButton9"
NO_SAVE_SESSION_BUTTON_CSS_SELECTOR = "#idBtn_Back"
UNCHECKED_CARDS_CSS_SELECTOR = "mee-card .mee-icon-AddMedium"
REJECT_COOKIE_BUTTON_CSS_SELECTOR = "#bnp_btn_reject"
START_TEST_BUTTON_CSS_SELECTOR = "#rqStartQuiz"
TEXT_EXTRA_OPTIONS_CSS_SELECTOR = "#QuizContainerWrapper .slide"
TEXT_EXTRA_OPTION_SELECTED_CSS_SELECTOR = ".b_hide"
BING_LOGIN_BUTTON_CSS_SELECTOR = "#id_l"
SHOW_DAILY_POINTS_LINK_CSS_SELECTOR = "#dailypointColumnCalltoAction"
ALL_CARDS_POINTS_CSS_SELECTOR = ".cardContainer .title-detail"
CARD_POINTS_TEXT_CSS_SELECTOR = "a"
POINTS_COMPLETED_CSS_SELECTOR = "p b"
POINTS_TO_COMPLETE_CSS_SELECTOR = ".pointsDetail"